/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package laundry;
import java.awt.*;
import javax.swing.JOptionPane;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Date;
/**
 *
 * @author RobinKeya
 */
public class CustomerReg extends javax.swing.JFrame {
    int duvet,bedsheets,suits,gradgown,wedgown,tablecloth,normalcloth,towel;
    /**
     * Creates new form CustomerReg
     */
    public CustomerReg() {
        initComponents();
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtFirstName1 = new javax.swing.JTextField();
        txtMobileNumber = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtIDNumber1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtDateIn = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jcombobxCustomerType = new javax.swing.JComboBox<>();
        jpanelCLothes1 = new javax.swing.JPanel();
        jcheckboxDuvet1 = new javax.swing.JCheckBox();
        jcheckboxTowel1 = new javax.swing.JCheckBox();
        jcheckbxBedsheets1 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jchekboxSuits1 = new javax.swing.JCheckBox();
        jcheckboxGradGown1 = new javax.swing.JCheckBox();
        jchekBoxWedGown2 = new javax.swing.JCheckBox();
        jchekBoxWedGown3 = new javax.swing.JCheckBox();
        txtContacts = new javax.swing.JTextField();
        jpanelMain = new javax.swing.JPanel();
        jpanelCLothes = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        txtDuvetQuantity = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtBedSheetsQuantity = new javax.swing.JTextField();
        txtTowelQuantity = new javax.swing.JTextField();
        txtTableClothQuantity = new javax.swing.JTextField();
        txtgradGownQuantity = new javax.swing.JTextField();
        txtWeddingGownQuantity = new javax.swing.JTextField();
        txtSuitsQuantity = new javax.swing.JTextField();
        txtNormalClothingQuantity = new javax.swing.JTextField();
        lblDuvets = new javax.swing.JLabel();
        lblBedSheets = new javax.swing.JLabel();
        lblTowels = new javax.swing.JLabel();
        lblTableClothes = new javax.swing.JLabel();
        lblGradGown = new javax.swing.JLabel();
        lblWedGown = new javax.swing.JLabel();
        lblSuits = new javax.swing.JLabel();
        lblNormClothes = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtIDNumber = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jcombobxCustomerType1 = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        txtContacts1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtDateIn1 = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();
        btnAddNew = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        btnCost = new javax.swing.JButton();
        txtTotalCost = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jcombobxShelfNumber = new javax.swing.JComboBox<>();

        jFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jFrame1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setText("First Name");

        jLabel4.setText("Customer");

        jLabel5.setText("Contacts");

        jLabel7.setText("ID Number");

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Add New");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Home");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel8.setText("Date In");

        txtDateIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtDateInMouseClicked(evt);
            }
        });
        txtDateIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDateInActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("CUSTOMER REGISTRATION");

        jcombobxCustomerType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Student/Stuff", "Outsiders" }));

        jpanelCLothes1.setBackground(new java.awt.Color(255, 255, 255));

        jcheckboxDuvet1.setText("Duvet/Blankets");
        jcheckboxDuvet1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcheckboxDuvet1ItemStateChanged(evt);
            }
        });

        jcheckboxTowel1.setText("Towel");
        jcheckboxTowel1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcheckboxTowel1ItemStateChanged(evt);
            }
        });

        jcheckbxBedsheets1.setText("Bedsheet");
        jcheckbxBedsheets1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcheckbxBedsheets1ItemStateChanged(evt);
            }
        });

        jCheckBox5.setText("Table Clothes");
        jCheckBox5.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBox5ItemStateChanged(evt);
            }
        });

        jchekboxSuits1.setText("Suits");
        jchekboxSuits1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jchekboxSuits1ItemStateChanged(evt);
            }
        });

        jcheckboxGradGown1.setText("Graduation Gown");

        jchekBoxWedGown2.setText("Wedding Gown");

        jchekBoxWedGown3.setText("Normal Clothings");

        javax.swing.GroupLayout jpanelCLothes1Layout = new javax.swing.GroupLayout(jpanelCLothes1);
        jpanelCLothes1.setLayout(jpanelCLothes1Layout);
        jpanelCLothes1Layout.setHorizontalGroup(
            jpanelCLothes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelCLothes1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jpanelCLothes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcheckboxDuvet1)
                    .addComponent(jcheckbxBedsheets1)
                    .addComponent(jcheckboxTowel1)
                    .addComponent(jCheckBox5))
                .addGap(50, 50, 50)
                .addGroup(jpanelCLothes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jchekBoxWedGown2)
                    .addComponent(jcheckboxGradGown1)
                    .addComponent(jchekboxSuits1)
                    .addComponent(jchekBoxWedGown3))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jpanelCLothes1Layout.setVerticalGroup(
            jpanelCLothes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelCLothes1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jpanelCLothes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcheckboxDuvet1)
                    .addComponent(jcheckboxGradGown1))
                .addGap(29, 29, 29)
                .addGroup(jpanelCLothes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcheckbxBedsheets1)
                    .addComponent(jchekBoxWedGown2))
                .addGap(31, 31, 31)
                .addGroup(jpanelCLothes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcheckboxTowel1)
                    .addComponent(jchekboxSuits1))
                .addGap(29, 29, 29)
                .addGroup(jpanelCLothes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox5)
                    .addComponent(jchekBoxWedGown3))
                .addContainerGap(79, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8))
                .addGap(35, 35, 35)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtMobileNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                    .addComponent(txtFirstName1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtIDNumber1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDateIn)
                    .addComponent(jcombobxCustomerType, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtContacts, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(jpanelCLothes1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(38, 38, 38)
                .addComponent(jButton2)
                .addGap(36, 36, 36)
                .addComponent(jButton3)
                .addGap(149, 149, 149))
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel9)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFrame1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(txtMobileNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jFrame1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jpanelCLothes1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jFrame1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtFirstName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtIDNumber1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jcombobxCustomerType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtContacts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtDateIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(67, 67, 67))
                    .addGroup(jFrame1Layout.createSequentialGroup()
                        .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addComponent(jButton3))
                        .addContainerGap())))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jpanelMain.setBackground(new java.awt.Color(255, 255, 255));

        jpanelCLothes.setBackground(new java.awt.Color(255, 255, 255));

        jLabel13.setText("Quantity");

        jLabel14.setText("Quantity");

        lblDuvets.setText("Duvet/Blankets");

        lblBedSheets.setText("Bed Sheets");

        lblTowels.setText("Towels");

        lblTableClothes.setText("Table Clothes");

        lblGradGown.setText("Graduation Gown");

        lblWedGown.setText("Wedding Gown");

        lblSuits.setText("Suits");

        lblNormClothes.setText("Normal Clothing");

        javax.swing.GroupLayout jpanelCLothesLayout = new javax.swing.GroupLayout(jpanelCLothes);
        jpanelCLothes.setLayout(jpanelCLothesLayout);
        jpanelCLothesLayout.setHorizontalGroup(
            jpanelCLothesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelCLothesLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jpanelCLothesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTableClothes)
                    .addComponent(lblTowels)
                    .addComponent(lblBedSheets)
                    .addGroup(jpanelCLothesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel13)
                        .addGroup(jpanelCLothesLayout.createSequentialGroup()
                            .addComponent(lblDuvets)
                            .addGap(35, 35, 35)
                            .addGroup(jpanelCLothesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtBedSheetsQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtDuvetQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtTowelQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtTableClothQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(13, 13, 13)
                .addGroup(jpanelCLothesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanelCLothesLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jpanelCLothesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpanelCLothesLayout.createSequentialGroup()
                                .addComponent(lblWedGown)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtWeddingGownQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpanelCLothesLayout.createSequentialGroup()
                                .addComponent(lblGradGown)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                                .addComponent(txtgradGownQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpanelCLothesLayout.createSequentialGroup()
                                .addComponent(lblSuits)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtSuitsQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpanelCLothesLayout.createSequentialGroup()
                                .addComponent(lblNormClothes)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtNormalClothingQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelCLothesLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel14)))
                .addContainerGap())
        );
        jpanelCLothesLayout.setVerticalGroup(
            jpanelCLothesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelCLothesLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jpanelCLothesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addGap(9, 9, 9)
                .addGroup(jpanelCLothesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDuvetQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtgradGownQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDuvets)
                    .addComponent(lblGradGown))
                .addGap(32, 32, 32)
                .addGroup(jpanelCLothesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBedSheetsQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtWeddingGownQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBedSheets)
                    .addComponent(lblWedGown))
                .addGap(34, 34, 34)
                .addGroup(jpanelCLothesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTowelQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSuitsQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTowels)
                    .addComponent(lblSuits))
                .addGap(32, 32, 32)
                .addGroup(jpanelCLothesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTableClothQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNormalClothingQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTableClothes)
                    .addComponent(lblNormClothes))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("CUSTOMER REGISTRATION");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(jLabel2)
                .addContainerGap(214, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel2)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jLabel1.setText("First Name");

        jLabel6.setText("ID Number");

        jLabel10.setText("Customer");

        jcombobxCustomerType1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Student/Stuff", "Outsiders" }));

        jLabel11.setText("Contacts");

        jLabel12.setText("Date In");

        txtDateIn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtDateIn1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtDateIn1MouseEntered(evt);
            }
        });
        txtDateIn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDateIn1ActionPerformed(evt);
            }
        });

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        btnAddNew.setText("Add New");
        btnAddNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewActionPerformed(evt);
            }
        });

        btnHome.setText("Home");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        btnCost.setText("Cost");
        btnCost.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCostMouseClicked(evt);
            }
        });
        btnCost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCostActionPerformed(evt);
            }
        });

        txtTotalCost.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtTotalCostMouseClicked(evt);
            }
        });

        jLabel15.setText("Shelf Number");

        jcombobxShelfNumber.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        javax.swing.GroupLayout jpanelMainLayout = new javax.swing.GroupLayout(jpanelMain);
        jpanelMain.setLayout(jpanelMainLayout);
        jpanelMainLayout.setHorizontalGroup(
            jpanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelMainLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jpanelMainLayout.createSequentialGroup()
                .addGroup(jpanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanelMainLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jpanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpanelMainLayout.createSequentialGroup()
                                .addGroup(jpanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jpanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtIDNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jpanelMainLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcombobxCustomerType1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpanelMainLayout.createSequentialGroup()
                                .addGroup(jpanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jpanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtContacts1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDateIn1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jpanelMainLayout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcombobxShelfNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jpanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpanelMainLayout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jpanelCLothes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelMainLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCost)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTotalCost, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(73, 73, 73))))
                    .addGroup(jpanelMainLayout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(btnSubmit)
                        .addGap(40, 40, 40)
                        .addComponent(btnAddNew)
                        .addGap(43, 43, 43)
                        .addComponent(btnHome)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpanelMainLayout.setVerticalGroup(
            jpanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelMainLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(jpanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanelMainLayout.createSequentialGroup()
                        .addComponent(jpanelCLothes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCost)
                            .addComponent(txtTotalCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(jpanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAddNew)
                            .addComponent(btnSubmit)
                            .addComponent(btnHome)))
                    .addGroup(jpanelMainLayout.createSequentialGroup()
                        .addGroup(jpanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(jpanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtIDNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(jpanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jcombobxCustomerType1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(jpanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtContacts1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(jpanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDateIn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(26, 26, 26)
                        .addGroup(jpanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jcombobxShelfNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpanelMain, javax.swing.GroupLayout.PREFERRED_SIZE, 610, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpanelMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        txtFirstName.setText("");
        txtMobileNumber.setText("");
        txtIDNumber.setText("");
        txtDateIn.setText("");

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
        Home a =new Home();
        //a.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtDateInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDateInMouseClicked

    }//GEN-LAST:event_txtDateInMouseClicked

    private void txtDateInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDateInActionPerformed

    private void jcheckboxDuvet1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcheckboxDuvet1ItemStateChanged
        //duvet = Integer.parseInt(JOptionPane.showInputDialog(this, "Quantity")); 
    }//GEN-LAST:event_jcheckboxDuvet1ItemStateChanged

    private void jcheckboxTowel1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcheckboxTowel1ItemStateChanged
        
// TODO add your handling code here:
    }//GEN-LAST:event_jcheckboxTowel1ItemStateChanged

    private void jcheckbxBedsheets1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcheckbxBedsheets1ItemStateChanged
       
// TODO add your handling code here:
    }//GEN-LAST:event_jcheckbxBedsheets1ItemStateChanged

    private void jCheckBox5ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBox5ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox5ItemStateChanged

    private void jchekboxSuits1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jchekboxSuits1ItemStateChanged
       //suits = Integer.parseInt(JOptionPane.showInputDialog(this, "Quantity"));
        // TODO add your handling code here:
    }//GEN-LAST:event_jchekboxSuits1ItemStateChanged

    private void txtDateIn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDateIn1MouseClicked
        Date date = new Date();
        SimpleDateFormat ft = new SimpleDateFormat("yyyy.MM.dd");
        String x = ft.format(date);
        txtDateIn1.setText(x);
        
    }//GEN-LAST:event_txtDateIn1MouseClicked

    private void txtDateIn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateIn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDateIn1ActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        Connection con = null;
        PreparedStatement pst = null;
        ResultSet rs = null;
        try{
            String sql="insert into Customer (Firstname,IDNumber,Customer,contacts,DateIn,DuvetQty,BedsheetsQty,"
            + "TowelQty,TableClothesQty,GradGownQty,WedGownQty,SuitsQty,NormalClothingQty,Total_cost,Shelf_no) values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
            con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/Laundry","root","");
            pst = (PreparedStatement) con.prepareStatement(sql);
            pst.setString(1,txtFirstName.getText());
            pst.setString(2,txtIDNumber.getText());
            pst.setString(3,String.valueOf(jcombobxCustomerType1.getSelectedItem()));
            pst.setString(4,txtContacts1.getText());
            pst.setString(5,txtDateIn1.getText());
            pst.setString(6,txtDuvetQuantity.getText());
            pst.setString(7,txtBedSheetsQuantity.getText());
            pst.setString(8,txtTowelQuantity.getText());
            pst.setString(9,txtTableClothQuantity.getText());
            pst.setString(10,txtgradGownQuantity.getText());
            pst.setString(11,txtWeddingGownQuantity.getText());
            pst.setString(12,txtSuitsQuantity.getText());
            pst.setString(13,txtNormalClothingQuantity.getText());
            pst.setString(14,txtTotalCost.getText());
            pst.setString(15,String.valueOf(jcombobxShelfNumber.getSelectedItem()));
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Enry successfully submitted");
        }
        catch(SQLException ex){
            JOptionPane.showMessageDialog(null, ex);
        } 
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSubmitActionPerformed
public int paymentfunction(){
    int cost = 0;
    duvet = Integer.parseInt(txtDuvetQuantity.getText());
    bedsheets = Integer.parseInt(txtBedSheetsQuantity.getText());
    towel = Integer.parseInt(txtTowelQuantity.getText());
    tablecloth = Integer.parseInt(txtTableClothQuantity.getText());
    gradgown = Integer.parseInt(txtgradGownQuantity.getText());
    wedgown = Integer.parseInt(txtWeddingGownQuantity.getText());
    suits = Integer.parseInt(txtSuitsQuantity.getText());
    normalcloth = Integer.parseInt(txtNormalClothingQuantity.getText());
    if(jcombobxCustomerType1.getSelectedIndex()==0){
        cost = (duvet * 300)+(bedsheets * 200)+ (towel * 120)+ (tablecloth * 2000)+(gradgown * 1500)+(wedgown * 2000)+
            (suits * 350)+ (normalcloth * 100);
    }
    else{
        cost = (duvet * 500)+(bedsheets * 300)+ (towel * 200)+ (tablecloth * 2500)+(gradgown * 2000)+(wedgown * 2500)+
            (suits * 500)+ (normalcloth * 150);
    }
    
  return cost;  
}
    
    private void btnAddNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewActionPerformed
        txtFirstName.setText("");
        txtIDNumber.setText("");
        txtContacts1.setText("");
        txtDateIn1.setText("");
        txtDuvetQuantity.setText("");
        txtBedSheetsQuantity.setText("");
        txtTowelQuantity.setText("");
        txtTableClothQuantity.setText("");
        txtgradGownQuantity.setText("");
        txtWeddingGownQuantity.setText("");
        txtSuitsQuantity.setText("");
        txtNormalClothingQuantity.setText("");

        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddNewActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        
        Home a =new Home();
        a.setVisible(true);this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_btnHomeActionPerformed

    private void txtDateIn1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDateIn1MouseEntered
       /* Date date = new Date();
        SimpleDateFormat ft = new SimpleDateFormat("dd.mm.yyyy");
        String x = ft.format(date);
        txtDateIn.setText(x);  */      // TODO add your handling code here:
    }//GEN-LAST:event_txtDateIn1MouseEntered

    private void btnCostMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCostMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCostMouseClicked

    private void btnCostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCostActionPerformed
         int x = paymentfunction();
         txtTotalCost.setText(x + " ");
    }//GEN-LAST:event_btnCostActionPerformed

    private void txtTotalCostMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTotalCostMouseClicked

    }//GEN-LAST:event_txtTotalCostMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerReg().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddNew;
    private javax.swing.JButton btnCost;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JCheckBox jcheckboxDuvet1;
    private javax.swing.JCheckBox jcheckboxGradGown1;
    private javax.swing.JCheckBox jcheckboxTowel1;
    private javax.swing.JCheckBox jcheckbxBedsheets1;
    private javax.swing.JCheckBox jchekBoxWedGown2;
    private javax.swing.JCheckBox jchekBoxWedGown3;
    private javax.swing.JCheckBox jchekboxSuits1;
    private javax.swing.JComboBox<String> jcombobxCustomerType;
    private javax.swing.JComboBox<String> jcombobxCustomerType1;
    private javax.swing.JComboBox<String> jcombobxShelfNumber;
    private javax.swing.JPanel jpanelCLothes;
    private javax.swing.JPanel jpanelCLothes1;
    private javax.swing.JPanel jpanelMain;
    private javax.swing.JLabel lblBedSheets;
    private javax.swing.JLabel lblDuvets;
    private javax.swing.JLabel lblGradGown;
    private javax.swing.JLabel lblNormClothes;
    private javax.swing.JLabel lblSuits;
    private javax.swing.JLabel lblTableClothes;
    private javax.swing.JLabel lblTowels;
    private javax.swing.JLabel lblWedGown;
    private javax.swing.JTextField txtBedSheetsQuantity;
    private javax.swing.JTextField txtContacts;
    private javax.swing.JTextField txtContacts1;
    private javax.swing.JTextField txtDateIn;
    private javax.swing.JTextField txtDateIn1;
    private javax.swing.JTextField txtDuvetQuantity;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtFirstName1;
    private javax.swing.JTextField txtIDNumber;
    private javax.swing.JTextField txtIDNumber1;
    private javax.swing.JTextField txtMobileNumber;
    private javax.swing.JTextField txtNormalClothingQuantity;
    private javax.swing.JTextField txtSuitsQuantity;
    private javax.swing.JTextField txtTableClothQuantity;
    private javax.swing.JTextField txtTotalCost;
    private javax.swing.JTextField txtTowelQuantity;
    private javax.swing.JTextField txtWeddingGownQuantity;
    private javax.swing.JTextField txtgradGownQuantity;
    // End of variables declaration//GEN-END:variables
}
