/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package laundry;

import java.sql.DriverManager;
import javax.swing.JOptionPane;
import java.sql.*;

/**
 *
 * @author RobinKeya
 */
public class EditCustomerData extends javax.swing.JFrame {
Connection con =null;
PreparedStatement pst = null;
ResultSet rs= null;
    /**
     * Creates new form EditCustomerData
     */
    public EditCustomerData() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpanelMain = new javax.swing.JPanel();
        jpanelCLothes = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        txtDuvetQuantity = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtBedSheetsQuantity = new javax.swing.JTextField();
        txtTowelQuantity = new javax.swing.JTextField();
        txtTableClothQuantity = new javax.swing.JTextField();
        txtgradGownQuantity = new javax.swing.JTextField();
        txtWeddingGownQuantity = new javax.swing.JTextField();
        txtSuitsQuantity = new javax.swing.JTextField();
        txtNormalClothingQuantity = new javax.swing.JTextField();
        lblDuvets = new javax.swing.JLabel();
        lblBedSheets = new javax.swing.JLabel();
        lblTowels = new javax.swing.JLabel();
        lblTableClothes = new javax.swing.JLabel();
        lblGradGown = new javax.swing.JLabel();
        lblWedGown = new javax.swing.JLabel();
        lblSuits = new javax.swing.JLabel();
        lblNormClothes = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtIDNumber = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jcombobxCustomerType1 = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        txtContacts1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtDateIn1 = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        btnCost = new javax.swing.JButton();
        txtTotalCost = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jcombobxShelfNumber = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpanelMain.setBackground(new java.awt.Color(255, 255, 255));

        jpanelCLothes.setBackground(new java.awt.Color(255, 255, 255));

        jLabel13.setText("Quantity");

        jLabel14.setText("Quantity");

        lblDuvets.setText("Duvet/Blankets");

        lblBedSheets.setText("Bed Sheets");

        lblTowels.setText("Towels");

        lblTableClothes.setText("Table Clothes");

        lblGradGown.setText("Graduation Gown");

        lblWedGown.setText("Wedding Gown");

        lblSuits.setText("Suits");

        lblNormClothes.setText("Normal Clothing");

        javax.swing.GroupLayout jpanelCLothesLayout = new javax.swing.GroupLayout(jpanelCLothes);
        jpanelCLothes.setLayout(jpanelCLothesLayout);
        jpanelCLothesLayout.setHorizontalGroup(
            jpanelCLothesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelCLothesLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jpanelCLothesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTableClothes)
                    .addComponent(lblTowels)
                    .addComponent(lblBedSheets)
                    .addGroup(jpanelCLothesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel13)
                        .addGroup(jpanelCLothesLayout.createSequentialGroup()
                            .addComponent(lblDuvets)
                            .addGap(35, 35, 35)
                            .addGroup(jpanelCLothesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtBedSheetsQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtDuvetQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtTowelQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtTableClothQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(13, 13, 13)
                .addGroup(jpanelCLothesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanelCLothesLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jpanelCLothesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpanelCLothesLayout.createSequentialGroup()
                                .addComponent(lblWedGown)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtWeddingGownQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpanelCLothesLayout.createSequentialGroup()
                                .addComponent(lblGradGown)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                                .addComponent(txtgradGownQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpanelCLothesLayout.createSequentialGroup()
                                .addComponent(lblSuits)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtSuitsQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpanelCLothesLayout.createSequentialGroup()
                                .addComponent(lblNormClothes)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtNormalClothingQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jpanelCLothesLayout.setVerticalGroup(
            jpanelCLothesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelCLothesLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jpanelCLothesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addGap(9, 9, 9)
                .addGroup(jpanelCLothesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDuvetQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtgradGownQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDuvets)
                    .addComponent(lblGradGown))
                .addGap(32, 32, 32)
                .addGroup(jpanelCLothesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBedSheetsQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtWeddingGownQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBedSheets)
                    .addComponent(lblWedGown))
                .addGap(34, 34, 34)
                .addGroup(jpanelCLothesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTowelQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSuitsQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTowels)
                    .addComponent(lblSuits))
                .addGap(32, 32, 32)
                .addGroup(jpanelCLothesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTableClothQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNormalClothingQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTableClothes)
                    .addComponent(lblNormClothes))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("CUSTOMER REGISTRATION");

        jLabel3.setText("Search By ID");

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap(214, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)))
        );

        jLabel1.setText("First Name");

        jLabel6.setText("ID Number");

        jLabel10.setText("Customer");

        jcombobxCustomerType1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Student/Stuff", "Outsiders" }));

        jLabel11.setText("Contacts");

        jLabel12.setText("Date In");

        txtDateIn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtDateIn1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtDateIn1MouseEntered(evt);
            }
        });
        txtDateIn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDateIn1ActionPerformed(evt);
            }
        });

        btnSubmit.setText("Update");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnHome.setText("Home");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        btnCost.setText("Cost");
        btnCost.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCostMouseClicked(evt);
            }
        });
        btnCost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCostActionPerformed(evt);
            }
        });

        txtTotalCost.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtTotalCostMouseClicked(evt);
            }
        });

        jLabel15.setText("Shelf Number");

        jcombobxShelfNumber.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        javax.swing.GroupLayout jpanelMainLayout = new javax.swing.GroupLayout(jpanelMain);
        jpanelMain.setLayout(jpanelMainLayout);
        jpanelMainLayout.setHorizontalGroup(
            jpanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelMainLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jpanelMainLayout.createSequentialGroup()
                .addGroup(jpanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanelMainLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jpanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpanelMainLayout.createSequentialGroup()
                                .addGroup(jpanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jpanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtIDNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jpanelMainLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcombobxCustomerType1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpanelMainLayout.createSequentialGroup()
                                .addGroup(jpanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jpanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtContacts1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDateIn1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jpanelMainLayout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcombobxShelfNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jpanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpanelMainLayout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jpanelCLothes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelMainLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCost)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTotalCost, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(73, 73, 73))))
                    .addGroup(jpanelMainLayout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(btnSubmit)
                        .addGap(40, 40, 40)
                        .addComponent(btnDelete)
                        .addGap(43, 43, 43)
                        .addComponent(btnHome)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpanelMainLayout.setVerticalGroup(
            jpanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelMainLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(jpanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanelMainLayout.createSequentialGroup()
                        .addComponent(jpanelCLothes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCost)
                            .addComponent(txtTotalCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(jpanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDelete)
                            .addComponent(btnSubmit)
                            .addComponent(btnHome)))
                    .addGroup(jpanelMainLayout.createSequentialGroup()
                        .addGroup(jpanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(jpanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtIDNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(jpanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jcombobxCustomerType1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(jpanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtContacts1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(jpanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDateIn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(26, 26, 26)
                        .addGroup(jpanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jcombobxShelfNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpanelMain, javax.swing.GroupLayout.PREFERRED_SIZE, 610, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtDateIn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDateIn1MouseClicked

    }//GEN-LAST:event_txtDateIn1MouseClicked

    private void txtDateIn1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDateIn1MouseEntered
        /* Date date = new Date();
        SimpleDateFormat ft = new SimpleDateFormat("dd.mm.yyyy");
        String x = ft.format(date);
        txtDateIn.setText(x);  */      // TODO add your handling code here:
    }//GEN-LAST:event_txtDateIn1MouseEntered

    private void txtDateIn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateIn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDateIn1ActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
         try{
            String sql = "UPDATE Customer"
         + " SET FirstName=?,IDNumber=?,Customer=?,Contacts=?,DuvetQty=?,BedsheetsQty=?"
                    + ",TowelQty=?,TableClothesQty=?,GradGownQty=?,WedGownQty=?,SuitsQty=?,"
                    + "NormalClothingQty=?,total_cost=?,shelf_no=?"
         + "WHERE IDNumber = ?";
 con = DriverManager.getConnection("jdbc:mysql://localhost/Laundry","root","");
 pst = con.prepareStatement(sql);
 pst.setString(1,txtFirstName.getText());
            pst.setString(2,txtIDNumber.getText());
            pst.setString(3,String.valueOf(jcombobxCustomerType1.getSelectedItem()));
            pst.setString(4,txtContacts1.getText());
            pst.setString(5,txtDateIn1.getText());
            pst.setString(6,txtDuvetQuantity.getText());
            pst.setString(7,txtBedSheetsQuantity.getText());
            pst.setString(8,txtTowelQuantity.getText());
            pst.setString(9,txtTableClothQuantity.getText());
            pst.setString(10,txtgradGownQuantity.getText());
            pst.setString(11,txtWeddingGownQuantity.getText());
            pst.setString(12,txtSuitsQuantity.getText());
            pst.setString(13,txtNormalClothingQuantity.getText());
            pst.setString(14,txtTotalCost.getText());
            pst.setString(15,String.valueOf(jcombobxShelfNumber.getSelectedItem()));
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Update Successfull");
        }
        catch(SQLException ex){
            JOptionPane.showMessageDialog(null, ex);
        }// TODO add your handling code here:
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
       
try{
            String sql ="Delete from Customer where IDNumber = ?";
            con = DriverManager.getConnection("jdbc:mysql://localhost/Laundry","root","");
            pst = con.prepareStatement(sql);
            pst.setString(1,txtIDNumber.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Successfull");
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null, ex);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        this.setVisible(false);
        Home a =new Home();
        a.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnCostMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCostMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCostMouseClicked

    private void btnCostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCostActionPerformed

    }//GEN-LAST:event_btnCostActionPerformed

    private void txtTotalCostMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTotalCostMouseClicked

    }//GEN-LAST:event_txtTotalCostMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    try{
           String sql="select  * from  Customer where IDNumber=?";
               con = DriverManager.getConnection("jdbc:mysql://localhost/Laundry","root","");
           
            pst=con.prepareStatement(sql);
            pst.setString(1, txtSearch.getText());

            rs=pst.executeQuery();

           if(rs.next())
            {

                String add1=rs.getString("FirstName");
                txtFirstName.setText(add1);

                String add2=rs.getString("IDNumber");
                txtIDNumber.setText(add2);

                String add3=rs.getString("Customer");
                jcombobxCustomerType1.setSelectedItem(add3);
                
                 String add4=rs.getString("Contacts");
                txtContacts1.setText(add4);
                

                String add5=rs.getString("Shelf_no");
                jcombobxShelfNumber.setSelectedItem(add5);

                String add6=rs.getString("DuvetQty");
                txtDuvetQuantity.setText(add6);

                String add7=rs.getString("BedsheetsQty");
                txtBedSheetsQuantity.setText(add7);

                String add8=rs.getString("TowelQty");
                txtTowelQuantity.setText(add8);

                String add9=rs.getString("TableClothesQty");
                txtTableClothQuantity.setText(add9);

                String add10=rs.getString("GradGownQty");
                txtgradGownQuantity.setText(add10);

                String add11=rs.getString("WedGownQty");
                txtWeddingGownQuantity.setText(add11);
                
                 String add12=rs.getString("SuitsQty");
                txtSuitsQuantity.setText(add12);
                 String add13=rs.getString("NormalClothingQty");
                txtNormalClothingQuantity.setText(add12);
                 String add14=rs.getString("Total_cost");
                txtTotalCost.setText(add14);
                 
            }
            
        else 
           {

                JOptionPane.showMessageDialog(null,"Not Found");
                 // JOptionPane.showMessageDialog(null,"Data Found.");
            }


        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        // TODO add your handling code here:
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditCustomerData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditCustomerData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditCustomerData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditCustomerData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditCustomerData().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCost;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> jcombobxCustomerType1;
    private javax.swing.JComboBox<String> jcombobxShelfNumber;
    private javax.swing.JPanel jpanelCLothes;
    private javax.swing.JPanel jpanelMain;
    private javax.swing.JLabel lblBedSheets;
    private javax.swing.JLabel lblDuvets;
    private javax.swing.JLabel lblGradGown;
    private javax.swing.JLabel lblNormClothes;
    private javax.swing.JLabel lblSuits;
    private javax.swing.JLabel lblTableClothes;
    private javax.swing.JLabel lblTowels;
    private javax.swing.JLabel lblWedGown;
    private javax.swing.JTextField txtBedSheetsQuantity;
    private javax.swing.JTextField txtContacts1;
    private javax.swing.JTextField txtDateIn1;
    private javax.swing.JTextField txtDuvetQuantity;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtIDNumber;
    private javax.swing.JTextField txtNormalClothingQuantity;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtSuitsQuantity;
    private javax.swing.JTextField txtTableClothQuantity;
    private javax.swing.JTextField txtTotalCost;
    private javax.swing.JTextField txtTowelQuantity;
    private javax.swing.JTextField txtWeddingGownQuantity;
    private javax.swing.JTextField txtgradGownQuantity;
    // End of variables declaration//GEN-END:variables
}
