/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package laundry;

import java.sql.DriverManager;
import javax.swing.JOptionPane;
import java.sql.*;

/**
 *
 * @author RobinKeya
 */
public class EditCustomer extends javax.swing.JFrame {
Connection con = null;
PreparedStatement pst = null;
ResultSet rs = null;
    /**
     * Creates new form EditCustomer
     */
    public EditCustomer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpanelMain = new javax.swing.JPanel();
        jpanelCLothes = new javax.swing.JPanel();
        jcheckboxDuvet = new javax.swing.JCheckBox();
        jcheckboxTowel = new javax.swing.JCheckBox();
        jcheckbxBedsheets = new javax.swing.JCheckBox();
        jcheckboxTableClothes = new javax.swing.JCheckBox();
        jchekboxSuits = new javax.swing.JCheckBox();
        jcheckboxGradGown = new javax.swing.JCheckBox();
        jchekBoxWedGown = new javax.swing.JCheckBox();
        jchekBoxNormalClothing = new javax.swing.JCheckBox();
        jLabel13 = new javax.swing.JLabel();
        txtDuvetQuantity = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtBedSheetsQuantity = new javax.swing.JTextField();
        txtTowelQuantity = new javax.swing.JTextField();
        txtTableClothQuantity = new javax.swing.JTextField();
        txtgradGownQuantity = new javax.swing.JTextField();
        txtWeddingGownQuantity = new javax.swing.JTextField();
        txtSuitsQuantity = new javax.swing.JTextField();
        txtNormalClothingQuantity = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtIDNumber = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jcombobxCustomerType1 = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        txtContacts1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtDateIn1 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        btnCost = new javax.swing.JButton();
        txtTotalCost = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jpanelMain.setBackground(new java.awt.Color(255, 255, 255));

        jpanelCLothes.setBackground(new java.awt.Color(255, 255, 255));

        jcheckboxDuvet.setBackground(java.awt.Color.white);
        jcheckboxDuvet.setText("Duvet/Blankets");
        jcheckboxDuvet.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcheckboxDuvetItemStateChanged(evt);
            }
        });
        jcheckboxDuvet.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jcheckboxDuvetStateChanged(evt);
            }
        });

        jcheckboxTowel.setBackground(java.awt.Color.white);
        jcheckboxTowel.setText("Towel");
        jcheckboxTowel.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcheckboxTowelItemStateChanged(evt);
            }
        });

        jcheckbxBedsheets.setBackground(java.awt.Color.white);
        jcheckbxBedsheets.setText("Bedsheet");
        jcheckbxBedsheets.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcheckbxBedsheetsItemStateChanged(evt);
            }
        });
        jcheckbxBedsheets.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jcheckbxBedsheetsStateChanged(evt);
            }
        });
        jcheckbxBedsheets.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jcheckbxBedsheetsMouseClicked(evt);
            }
        });

        jcheckboxTableClothes.setBackground(java.awt.Color.white);
        jcheckboxTableClothes.setText("Table Clothes");
        jcheckboxTableClothes.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcheckboxTableClothesItemStateChanged(evt);
            }
        });

        jchekboxSuits.setBackground(java.awt.Color.white);
        jchekboxSuits.setText("Suits");
        jchekboxSuits.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jchekboxSuitsItemStateChanged(evt);
            }
        });

        jcheckboxGradGown.setBackground(java.awt.Color.white);
        jcheckboxGradGown.setText("Graduation Gown");
        jcheckboxGradGown.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcheckboxGradGownItemStateChanged(evt);
            }
        });

        jchekBoxWedGown.setBackground(java.awt.Color.white);
        jchekBoxWedGown.setText("Wedding Gown");
        jchekBoxWedGown.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jchekBoxWedGownItemStateChanged(evt);
            }
        });

        jchekBoxNormalClothing.setBackground(java.awt.Color.white);
        jchekBoxNormalClothing.setText("Normal Clothings");
        jchekBoxNormalClothing.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jchekBoxNormalClothingItemStateChanged(evt);
            }
        });
        jchekBoxNormalClothing.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jchekBoxNormalClothingStateChanged(evt);
            }
        });

        jLabel13.setText("Quantity");

        jLabel14.setText("Quantity");

        javax.swing.GroupLayout jpanelCLothesLayout = new javax.swing.GroupLayout(jpanelCLothes);
        jpanelCLothes.setLayout(jpanelCLothesLayout);
        jpanelCLothesLayout.setHorizontalGroup(
            jpanelCLothesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelCLothesLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jpanelCLothesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jpanelCLothesLayout.createSequentialGroup()
                        .addComponent(jcheckbxBedsheets)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtBedSheetsQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpanelCLothesLayout.createSequentialGroup()
                        .addComponent(jcheckboxTowel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtTowelQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpanelCLothesLayout.createSequentialGroup()
                        .addComponent(jcheckboxTableClothes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTableClothQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpanelCLothesLayout.createSequentialGroup()
                        .addComponent(jcheckboxDuvet)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDuvetQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23)
                .addGroup(jpanelCLothesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanelCLothesLayout.createSequentialGroup()
                        .addComponent(jchekBoxWedGown)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtWeddingGownQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpanelCLothesLayout.createSequentialGroup()
                        .addComponent(jcheckboxGradGown)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtgradGownQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpanelCLothesLayout.createSequentialGroup()
                        .addComponent(jchekboxSuits)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtSuitsQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpanelCLothesLayout.createSequentialGroup()
                        .addComponent(jchekBoxNormalClothing)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtNormalClothingQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jpanelCLothesLayout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(19, 19, 19))
        );
        jpanelCLothesLayout.setVerticalGroup(
            jpanelCLothesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelCLothesLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jpanelCLothesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addGap(8, 8, 8)
                .addGroup(jpanelCLothesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcheckboxDuvet)
                    .addComponent(jcheckboxGradGown)
                    .addComponent(txtDuvetQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtgradGownQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jpanelCLothesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcheckbxBedsheets)
                    .addComponent(jchekBoxWedGown)
                    .addComponent(txtBedSheetsQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtWeddingGownQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jpanelCLothesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcheckboxTowel)
                    .addComponent(jchekboxSuits)
                    .addComponent(txtTowelQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSuitsQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jpanelCLothesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcheckboxTableClothes)
                    .addComponent(jchekBoxNormalClothing)
                    .addComponent(txtTableClothQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNormalClothingQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Edit Customer");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(224, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(152, 152, 152))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(19, 19, 19))
        );

        jLabel1.setText("First Name");

        jLabel6.setText("ID Number");

        jLabel10.setText("Customer");

        jcombobxCustomerType1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Student/Stuff", "Outsiders" }));

        jLabel11.setText("Contacts");

        jLabel12.setText("Date In");

        txtDateIn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtDateIn1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtDateIn1MouseEntered(evt);
            }
        });
        txtDateIn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDateIn1ActionPerformed(evt);
            }
        });

        jButton5.setText("Delete");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Home");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        btnCost.setText("Cost");
        btnCost.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCostMouseClicked(evt);
            }
        });
        btnCost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCostActionPerformed(evt);
            }
        });

        txtTotalCost.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtTotalCostMouseClicked(evt);
            }
        });

        jLabel3.setText("Search by ID");

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpanelMainLayout = new javax.swing.GroupLayout(jpanelMain);
        jpanelMain.setLayout(jpanelMainLayout);
        jpanelMainLayout.setHorizontalGroup(
            jpanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelMainLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jpanelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanelMainLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(txtDateIn1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel12)
                    .addGroup(jpanelMainLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtContacts1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpanelMainLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcombobxCustomerType1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpanelMainLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIDNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpanelMainLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpanelMainLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jpanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanelMainLayout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(btnCost)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTotalCost, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelMainLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(btnSearch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                        .addComponent(jpanelCLothes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(jpanelMainLayout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(jButton1)
                .addGap(32, 32, 32)
                .addComponent(jButton5)
                .addGap(43, 43, 43)
                .addComponent(jButton6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpanelMainLayout.setVerticalGroup(
            jpanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelMainLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(jpanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanelMainLayout.createSequentialGroup()
                        .addComponent(jpanelCLothes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCost)
                            .addComponent(txtTotalCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(jpanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton5)
                            .addComponent(jButton6)
                            .addComponent(jButton1)))
                    .addGroup(jpanelMainLayout.createSequentialGroup()
                        .addGroup(jpanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSearch))
                        .addGap(18, 18, 18)
                        .addGroup(jpanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(jpanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(txtIDNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(jpanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jcombobxCustomerType1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jpanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtContacts1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jpanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txtDateIn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jcheckboxDuvetItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcheckboxDuvetItemStateChanged
        // duvet =Integer.parseInt(JOptionPane.showInputDialog(null, "Quantity"));   // TODO add your handling code here:
    }//GEN-LAST:event_jcheckboxDuvetItemStateChanged

    private void jcheckboxDuvetStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jcheckboxDuvetStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jcheckboxDuvetStateChanged

    private void jcheckboxTowelItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcheckboxTowelItemStateChanged
        // towel = Integer.parseInt(JOptionPane.showInputDialog(this, "Quantity")); // TODO add your handling code here:
    }//GEN-LAST:event_jcheckboxTowelItemStateChanged

    private void jcheckbxBedsheetsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcheckbxBedsheetsItemStateChanged
        // bedsheets = Integer.parseInt(JOptionPane.showInputDialog(this, "Quantity")); // TODO add your handling code here:
    }//GEN-LAST:event_jcheckbxBedsheetsItemStateChanged

    private void jcheckbxBedsheetsStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jcheckbxBedsheetsStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jcheckbxBedsheetsStateChanged

    private void jcheckbxBedsheetsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcheckbxBedsheetsMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jcheckbxBedsheetsMouseClicked

    private void jcheckboxTableClothesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcheckboxTableClothesItemStateChanged
        // tablecloth = Integer.parseInt(JOptionPane.showInputDialog(this, "Quantity"));// TODO add your handling code here:
    }//GEN-LAST:event_jcheckboxTableClothesItemStateChanged

    private void jchekboxSuitsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jchekboxSuitsItemStateChanged
        //suits = Integer.parseInt(JOptionPane.showInputDialog(this, "Quantity in Kilos"));        // TODO add your handling code here:
    }//GEN-LAST:event_jchekboxSuitsItemStateChanged

    private void jcheckboxGradGownItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcheckboxGradGownItemStateChanged
        // gradgown = Integer.parseInt(JOptionPane.showInputDialog(this, "Quantity"));        // TODO add your handling code here:
    }//GEN-LAST:event_jcheckboxGradGownItemStateChanged

    private void jchekBoxWedGownItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jchekBoxWedGownItemStateChanged
        //wedgown = Integer.parseInt(JOptionPane.showInputDialog(this, "Quantity"));        // TODO add your handling code here:
    }//GEN-LAST:event_jchekBoxWedGownItemStateChanged

    private void jchekBoxNormalClothingItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jchekBoxNormalClothingItemStateChanged
        // normalcloth = Integer.parseInt(JOptionPane.showInputDialog(this, "Quantity in Kilos"));
        // TODO add your handling code here:
    }//GEN-LAST:event_jchekBoxNormalClothingItemStateChanged

    private void jchekBoxNormalClothingStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jchekBoxNormalClothingStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jchekBoxNormalClothingStateChanged

    private void txtDateIn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDateIn1MouseClicked


    }//GEN-LAST:event_txtDateIn1MouseClicked

    private void txtDateIn1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDateIn1MouseEntered
        /* Date date = new Date();
        SimpleDateFormat ft = new SimpleDateFormat("dd.mm.yyyy");
        String x = ft.format(date);
        txtDateIn.setText(x);  */      // TODO add your handling code here:
    }//GEN-LAST:event_txtDateIn1MouseEntered

    private void txtDateIn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateIn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDateIn1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
try{
         con = DriverManager.getConnection("jdbc:mysql://localhost/Laundry","root","");
        String sql = "DELETE FROM Customer"
         + "WHERE IDNumber=?";

 pst = con.prepareStatement(sql);
 pst.executeUpdate();
 JOptionPane.showMessageDialog(null, "Delete successful");
  
 }
 catch(SQLException ex){
 JOptionPane.showMessageDialog(null, ex);
 }         

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        this.setVisible(false);
        Home a =new Home();
        a.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void btnCostMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCostMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCostMouseClicked

    private void btnCostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCostActionPerformed

    private void txtTotalCostMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTotalCostMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalCostMouseClicked

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
try{
           String sql="select  * from  Customer where IDNumber=?";
               con = DriverManager.getConnection("jdbc:mysql://localhost/Laundry","root","");
           
            pst=con.prepareStatement(sql);
            pst.setString(1, txtSearch.getText());

            rs=pst.executeQuery();

           if(rs.next())
            {

                String add1=rs.getString("FirstName");
                txtFirstName.setText(add1);

                String add2=rs.getString("IDNumber");
                txtIDNumber.setText(add2);

                String add3=rs.getString("Customer");
                jcombobxCustomerType1.setSelectedItem(add3);
                
                 String add4=rs.getString("Contacts");
                txtContacts1.setText(add4);
                

                String add5=rs.getString("DateIn");
                txtDateIn1.setText(add5);

                String add6=rs.getString("DuvetQty");
                txtDuvetQuantity.setText(add6);

                String add7=rs.getString("BedSheetsQty");
                txtBedSheetsQuantity.setText(add7);

                String add8=rs.getString("TowelQty");
                txtTowelQuantity.setText(add8);

                String add9=rs.getString("TableClothesQty");
                txtTableClothQuantity.setText(add9);

                String add10=rs.getString("GradGownQty");
                txtgradGownQuantity.setText(add10);

                String add11=rs.getString("WedGownQty");
                txtWeddingGownQuantity.setText(add11);
                
                 String add12=rs.getString("SuitsQty");
                txtSuitsQuantity.setText(add12);
                 String add13=rs.getString("NormalClothingQty");
                txtNormalClothingQuantity.setText(add12);
            }
            
        else 
           {

                JOptionPane.showMessageDialog(null,"Not Found");
                 // JOptionPane.showMessageDialog(null,"Data Found.");
            }


        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"We face a Problem.");

        }
            // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 try{
 String sql = "UPDATE Customer"
         + " SET FirstName=?,IDNumber=?,Customer=?,Contacts=?,DuvetQty=?,BedsheetsQty=?"
       +"TableClothesQty=?,GradGownQty=?,WedGownQty=?,SuitsQty=?,NormalClothingQty=?"
         + "WHERE CustomerID=?";
 con = DriverManager.getConnection("jdbc:mysql://localhost/Laundry","root","");
 pst = con.prepareStatement(sql);
 pst.setString(1,txtFirstName.getText());
 pst.setString(2,txtIDNumber.getText());
 pst.setString(3,String.valueOf(jcombobxCustomerType1.getSelectedItem()));
 pst.setString(4,txtContacts1.getText());
 pst.setString(6,txtDuvetQuantity.getText());
 pst.setString(7,txtBedSheetsQuantity.getText());
 pst.setString(8,txtTowelQuantity.getText());
 pst.setString(9,txtTableClothQuantity.getText());
 pst.setString(10,txtgradGownQuantity.getText());
 pst.setString(11,txtWeddingGownQuantity.getText());
 pst.setString(12,txtSuitsQuantity.getText());
 pst.setString(13,txtNormalClothingQuantity.getText());
 pst.executeUpdate();
 JOptionPane.showMessageDialog(null, "updated successfully");
  
 }
 catch(SQLException ex){
 JOptionPane.showMessageDialog(null, ex);
 }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditCustomer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCost;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JCheckBox jcheckboxDuvet;
    private javax.swing.JCheckBox jcheckboxGradGown;
    private javax.swing.JCheckBox jcheckboxTableClothes;
    private javax.swing.JCheckBox jcheckboxTowel;
    private javax.swing.JCheckBox jcheckbxBedsheets;
    private javax.swing.JCheckBox jchekBoxNormalClothing;
    private javax.swing.JCheckBox jchekBoxWedGown;
    private javax.swing.JCheckBox jchekboxSuits;
    private javax.swing.JComboBox<String> jcombobxCustomerType1;
    private javax.swing.JPanel jpanelCLothes;
    private javax.swing.JPanel jpanelMain;
    private javax.swing.JTextField txtBedSheetsQuantity;
    private javax.swing.JTextField txtContacts1;
    private javax.swing.JTextField txtDateIn1;
    private javax.swing.JTextField txtDuvetQuantity;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtIDNumber;
    private javax.swing.JTextField txtNormalClothingQuantity;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtSuitsQuantity;
    private javax.swing.JTextField txtTableClothQuantity;
    private javax.swing.JTextField txtTotalCost;
    private javax.swing.JTextField txtTowelQuantity;
    private javax.swing.JTextField txtWeddingGownQuantity;
    private javax.swing.JTextField txtgradGownQuantity;
    // End of variables declaration//GEN-END:variables
}
