/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package laundry;
import javax.swing.*;

/**
 *
 * @author RobinKeya
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        this.setResizable(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        try {
            jDialog =(javax.swing.JLabel)java.beans.Beans.instantiate(getClass().getClassLoader(), "laundry.Home_jDialog");
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        } catch (java.io.IOException e) {
            e.printStackTrace();
        }
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuRegistration = new javax.swing.JMenu();
        mniCustomer = new javax.swing.JMenuItem();
        mniUser = new javax.swing.JMenuItem();
        mnuEdit = new javax.swing.JMenu();
        mniCustomerEdit = new javax.swing.JMenuItem();
        mniUserEdit = new javax.swing.JMenuItem();
        mnuView = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        mnuDispense = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        mniUsers = new javax.swing.JMenuItem();
        mniCustomers = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        mnuLogOut = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDialog.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jDialogAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        mnuRegistration.setBackground(new java.awt.Color(51, 0, 51));
        mnuRegistration.setForeground(new java.awt.Color(121, 0, 121));
        mnuRegistration.setText("NEW");
        mnuRegistration.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnuRegistration.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        mnuRegistration.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                mnuRegistrationPropertyChange(evt);
            }
        });

        mniCustomer.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mniCustomer.setForeground(new java.awt.Color(51, 0, 51));
        mniCustomer.setText("Customer");
        mniCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniCustomerActionPerformed(evt);
            }
        });
        mnuRegistration.add(mniCustomer);

        mniUser.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mniUser.setText("User");
        mniUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniUserActionPerformed(evt);
            }
        });
        mnuRegistration.add(mniUser);

        jMenuBar1.add(mnuRegistration);

        mnuEdit.setForeground(new java.awt.Color(121, 0, 121));
        mnuEdit.setText("Edit");
        mnuEdit.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        mniCustomerEdit.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mniCustomerEdit.setText("Customer");
        mniCustomerEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniCustomerEditActionPerformed(evt);
            }
        });
        mnuEdit.add(mniCustomerEdit);

        mniUserEdit.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mniUserEdit.setText("User");
        mniUserEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniUserEditActionPerformed(evt);
            }
        });
        mnuEdit.add(mniUserEdit);

        jMenuBar1.add(mnuEdit);

        mnuView.setForeground(new java.awt.Color(121, 0, 121));
        mnuView.setText("View");
        mnuView.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jMenuItem1.setText("Customer");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        mnuView.add(jMenuItem1);

        jMenuItem2.setText("User");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        mnuView.add(jMenuItem2);

        jMenuBar1.add(mnuView);

        mnuDispense.setForeground(new java.awt.Color(121, 0, 121));
        mnuDispense.setText("Dispense");
        mnuDispense.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        mnuDispense.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuDispenseMouseClicked(evt);
            }
        });
        jMenuBar1.add(mnuDispense);

        jMenu1.setText("Reports");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        mniUsers.setText("No. of Users");
        mniUsers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mniUsersMouseClicked(evt);
            }
        });
        mniUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniUsersActionPerformed(evt);
            }
        });
        jMenu1.add(mniUsers);

        mniCustomers.setText("No. of Customers");
        mniCustomers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mniCustomersMouseClicked(evt);
            }
        });
        mniCustomers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniCustomersActionPerformed(evt);
            }
        });
        jMenu1.add(mniCustomers);

        jMenuItem3.setText("Profit/Loss");
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        mnuLogOut.setForeground(new java.awt.Color(255, 0, 0));
        mnuLogOut.setText("Log Out");
        mnuLogOut.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                mnuLogOutMouseMoved(evt);
            }
        });
        mnuLogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuLogOutMouseClicked(evt);
            }
        });
        mnuLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuLogOutActionPerformed(evt);
            }
        });
        jMenuBar1.add(mnuLogOut);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDialog, javax.swing.GroupLayout.PREFERRED_SIZE, 1051, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDialog, javax.swing.GroupLayout.PREFERRED_SIZE, 697, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 47, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mniCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniCustomerActionPerformed

    CustomerReg j= new CustomerReg();
    j.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_mniCustomerActionPerformed

    private void mnuLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuLogOutActionPerformed
  
      //  System.exit(0);
        
       // TODO add your handling code here:
    }//GEN-LAST:event_mnuLogOutActionPerformed

    private void mnuLogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuLogOutMouseClicked
int s = JOptionPane.showConfirmDialog(this, "Sure to Log Out?");
        if(s==0){
        LogIn a= new LogIn();
        a.setVisible(true);
        this.setVisible(false);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_mnuLogOutMouseClicked

    private void mniUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniUserActionPerformed
           this.setVisible(true);
           User a= new User(this, rootPaneCheckingEnabled);
           a.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_mniUserActionPerformed

    private void mnuLogOutMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuLogOutMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuLogOutMouseMoved

    private void mnuRegistrationPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_mnuRegistrationPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuRegistrationPropertyChange

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        this.setVisible(true);
        Customer a= new Customer(this,rootPaneCheckingEnabled);
        a.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jDialogAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jDialogAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jDialogAncestorAdded

    private void mniCustomerEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniCustomerEditActionPerformed

    EditCustomerData a = new EditCustomerData();
    a.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_mniCustomerEditActionPerformed

    private void mniUserEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniUserEditActionPerformed
       this.setVisible(false);
       UserEdit a = new UserEdit(this, rootPaneCheckingEnabled);
        a.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_mniUserEditActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
    this.setVisible(true);
    UserView a = new UserView(this, rootPaneCheckingEnabled);
    a.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void mnuDispenseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuDispenseMouseClicked
this.setVisible(true);
Dispense pay = new Dispense();
pay.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_mnuDispenseMouseClicked

    private void mniUsersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mniUsersMouseClicked
// TODO add your handling code here:
    }//GEN-LAST:event_mniUsersMouseClicked

    private void mniCustomersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mniCustomersMouseClicked
// TODO add your handling code here:
    }//GEN-LAST:event_mniCustomersMouseClicked

    private void mniUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniUsersActionPerformed
    this.setVisible(true);
UsersReports a= new UsersReports();
a.setVisible(true);    // TODO add your handling code here:
    }//GEN-LAST:event_mniUsersActionPerformed

    private void mniCustomersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniCustomersActionPerformed
      this.setVisible(true);
        General a = new General();
a.setVisible(true);  // TODO add your handling code here:
    }//GEN-LAST:event_mniCustomersActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jDialog;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem mniCustomer;
    private javax.swing.JMenuItem mniCustomerEdit;
    private javax.swing.JMenuItem mniCustomers;
    private javax.swing.JMenuItem mniUser;
    private javax.swing.JMenuItem mniUserEdit;
    private javax.swing.JMenuItem mniUsers;
    private javax.swing.JMenu mnuDispense;
    private javax.swing.JMenu mnuEdit;
    private javax.swing.JMenu mnuLogOut;
    private javax.swing.JMenu mnuRegistration;
    private javax.swing.JMenu mnuView;
    // End of variables declaration//GEN-END:variables

   /* private void setVisible(String aFalse) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }*/
}
