/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package laundry;
import javax.swing.*;
/**
 *
 * @author RobinKeya
 */
public class Home1 extends javax.swing.JFrame {

    /**
     * Creates new form Home1
     */
    public Home1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuRegistration = new javax.swing.JMenu();
        mniCustomer = new javax.swing.JMenuItem();
        mnuDispense = new javax.swing.JMenu();
        mnuLogOut = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\RobinKeya\\Pictures\\Washateria-2.jpg")); // NOI18N
        jLabel1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabel1AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        mnuRegistration.setBackground(new java.awt.Color(51, 0, 51));
        mnuRegistration.setForeground(new java.awt.Color(121, 0, 121));
        mnuRegistration.setText("New Customer");
        mnuRegistration.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnuRegistration.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        mnuRegistration.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                mnuRegistrationPropertyChange(evt);
            }
        });

        mniCustomer.setForeground(new java.awt.Color(51, 0, 51));
        mniCustomer.setText("Customer");
        mniCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniCustomerActionPerformed(evt);
            }
        });
        mnuRegistration.add(mniCustomer);

        jMenuBar1.add(mnuRegistration);

        mnuDispense.setForeground(new java.awt.Color(121, 0, 121));
        mnuDispense.setText("Dispense");
        mnuDispense.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        mnuDispense.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuDispenseMouseClicked(evt);
            }
        });
        jMenuBar1.add(mnuDispense);

        mnuLogOut.setForeground(new java.awt.Color(255, 0, 0));
        mnuLogOut.setText("Log Out");
        mnuLogOut.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                mnuLogOutMouseMoved(evt);
            }
        });
        mnuLogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuLogOutMouseClicked(evt);
            }
        });
        mnuLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuLogOutActionPerformed(evt);
            }
        });
        jMenuBar1.add(mnuLogOut);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1051, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 697, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mniCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniCustomerActionPerformed
        this.setVisible(true);
        CustomerReg j= new CustomerReg();
        j.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_mniCustomerActionPerformed

    private void mnuRegistrationPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_mnuRegistrationPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuRegistrationPropertyChange

    private void mnuLogOutMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuLogOutMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuLogOutMouseMoved

    private void mnuLogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuLogOutMouseClicked
        int s = JOptionPane.showConfirmDialog(this, "Sure to Log Out?");
        if(s==0){
            LogIn a= new LogIn();
            a.setVisible(true);
            this.setVisible(false);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_mnuLogOutMouseClicked

    private void mnuLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuLogOutActionPerformed

        //  System.exit(0);

        // TODO add your handling code here:
    }//GEN-LAST:event_mnuLogOutActionPerformed

    private void jLabel1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabel1AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1AncestorAdded

    private void mnuDispenseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuDispenseMouseClicked
    Dispense1 a = new Dispense1();
    a.setVisible(true);
    // TODO add your handling code here:
    }//GEN-LAST:event_mnuDispenseMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mniCustomer;
    private javax.swing.JMenu mnuDispense;
    private javax.swing.JMenu mnuLogOut;
    private javax.swing.JMenu mnuRegistration;
    // End of variables declaration//GEN-END:variables
}
